name : Update Lambda Functions
on:
  push:
    branches:
      - dev
      - qa
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      lambdas: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          lambda1: 
            - 'lambda/**'
  deploy-lambdas:
    if: ${{ needs.changes.outputs.lambdas != '[]' }}
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        # e.g. ['lambda1', 'lambda2'] if both lambda folders contains changes
        lambdas: ${{ fromJSON(needs.changes.outputs.lambdas) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the name of filter
        run: |
          echo ${{ matrix.lambdas }}
          