name : lambda-deploy-dev
on:
  push:
    branches:
      - dev
jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::949263681218:role/ankit-oidc-role
          aws-region: us-east-1
      - name: Install zip
        run: |
          sudo apt install zip

      - name: Check for changes in lambda-1 directory
        id: lambda1-changed
        run: |
          git diff --quiet HEAD^ || echo "Changes detected"
        working-directory: lambda-1

      - name: Deploy lambda1
        if: steps.lambda1-changed.outputs.stdout == 'Changes detected'
        run: |
          cd lambda-1
          zip -r lambda_zip.zip *
          aws lambda update-function-code --function-name "lambda-1-${GITHUB_REF##*/}" --zip-file fileb://./lambda_zip.zip

      - name: Check for changes in lambda-2 directory
        id: lambda2-changed
        run: |
          git diff --quiet HEAD^ || echo "Changes detected"
        working-directory: lambda-2

      - name: Deploy lambda2
        if: steps.lambda2-changed.outputs.stdout == 'Changes detected'
        run: |
          cd lambda-2
          zip -r lambda_zip.zip *
          aws lambda update-function-code --function-name "lambda-2-${GITHUB_REF##*/}" --zip-file fileb://./lambda_zip.zip